#ifndef _MOURISL_CENTRIFUGER_ARGVDEFS
#define _MOURISL_CENTRIFUGER_ARGVDEFS

enum 
{
  ARGV_BMAX = 10000,
  ARGV_DCV,
  ARGV_OFFRATE,
  ARGV_TAXONOMY_TREE,
  ARGV_CONVERSION_TABLE,
  ARGV_NAME_TABLE,
  ARGV_SASORT_BLOCK
} ;

#endif
