#ifndef _MOURISL_CENTRIFUGER_ARGVDEFS
#define _MOURISL_CENTRIFUGER_ARGVDEFS

enum 
{
  ARGV_BMAX = 10000,
  ARGV_DCV,
  ARGV_BUILD_MEMORY,
  ARGV_OFFRATE,
  ARGV_FTABCHARS,
  ARGV_RBBWT_B,
  ARGV_TAXONOMY_TREE,
  ARGV_CONVERSION_TABLE,
  ARGV_NAME_TABLE,
  ARGV_SIZE_TABLE,
  ARGV_SUBSET_TAXONOMY,
  ARGV_MIN_HITLEN,
  ARGV_MAX_RESULT_PER_HIT_FACTOR,
  ARGV_MERGE_READ_PAIR,
  ARGV_READFORMAT,
  ARGV_SAMPLE_SHEET,
  ARGV_BARCODE,
  ARGV_UMI,
  ARGV_OUTPUT_UNCLASSIFIED,
  ARGV_OUTPUT_CLASSIFIED,
  ARGV_OUTPUT_EXPANDED_TAXIDS,
  ARGV_BARCODE_WHITELIST,
  ARGV_BARCODE_TRANSLATE,
  ARGV_BUILD_CONCAT_SAME_TAXID_SEQS,
  ARGV_BUILD_IGNORE_UNCATEGORIZED,
  ARGV_INSPECT_SUMMARY,
  ARGV_INSPECT_SEQNAME,
  ARGV_INSPECT_INDEXSIZE,
  ARGV_QUANT_MINSCORE,
  ARGV_QUANT_MINLENGTH,
  ARGV_QUANT_OUTPUT_FORMAT
} ;

#endif
