#ifndef _MOURISL_CENTRIFUGER_ARGVDEFS
#define _MOURISL_CENTRIFUGER_ARGVDEFS

enum 
{
  ARGV_BMAX = 10000,
  ARGV_DCV,
  ARGV_BUILD_MEMORY,
  ARGV_OFFRATE,
  ARGV_TAXONOMY_TREE,
  ARGV_CONVERSION_TABLE,
  ARGV_NAME_TABLE,
  ARGV_SUBSET_TAXONOMY,
  ARGV_MIN_HITLEN,
  ARGV_MAX_RESULT_PER_HIT_FACTOR,
  ARGV_MERGE_READ_PAIR,
  ARGV_INSPECT_SUMMARY,
  ARGV_INSPECT_SEQNAME,
  ARGV_INSPECT_INDEXSIZE
} ;

#endif
